# Alla sökvägar på ett ställe. Ändra bara här.
data_raw: data/raw
results: results
isescan_outdir: results/isescan
rustise_outdir: results/rust-ise
filtered_outdir: results/filtered
rustise_db: resources/rust-ise-db

# Körning
# scanner: rust-ise | isescan | both
scanner: rust-ise
nthread: 1
rustise_threads: 8
min_contig_bp: 500
remove_short_is: false
rustise_gpu: false
rustise_strict: false
