# Alla sökvägar på ett ställe. Ändra bara här.
data_raw: /home/eris/isescan-revisit/data/raw
results: results
isescan_outdir: results/isescan

# ISEScan-inställningar
nthread: 2
remove_short_is: false
