name: isescan-ml
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - pyyaml
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch
